### ISSUE TITLE
Screensaver activates while running games

### ISSUE THREAD

**Issue by JordanAnthonyKing** [basecamp/omarchy#1269]
When playing games with a controller the screensaver will activate as no mouse/keyboard input has been detected.

Specifically I'm using the dolphin emulator, I'll update if I find this is more widespread.

**Comment by JordanAnthonyKing** [comment]
The lock screen does too

**Comment by alexperreault** [comment]
This would be a problem upstream, with Hypridle

Tho I find it odd that it doesn't detect dolphin.

I'm pretty sure someone had this issue before you, you should search for Hypridle + dolphin

**Comment by JordanAnthonyKing** [comment]
> This would be a problem upstream, with Hypridle

Looking through hypridle issues looks like it’s an issue with our config:
https://github.com/hyprwm/hypridle/issues/53

I guess we need to add a .* rule for anything fullscreen to inhibit idle?

**Comment by JordanAnthonyKing** [comment]
Well I tried these two solutions to be a bit more intelligent about not activating the lock/screensaver unless the thing that was fullscreen was the screensaver itself but neither seemed to work. I'm using the plain `.*` rule for now. If anyone can show me what I had wrong that'd be greatly appreciated.
```
# Prevent screensaver/lock while running apps fullscreen
windowrule = idleinhibit fullscreen, class:.*
# windowrule = idleinhibit fullscreen, class:^(?!Screensaver$).*
# windowrule = idleinhibit fullscreen, class:^(?!.*Screensaver).*$
```

**Comment by dhh** [comment]
Solved via #1303.

**Comment by lukepighetti** [comment]
still having this issue on omarchy `4.0.2-1` 

clanker added this line to `~/.config/hypr/hyprland.lua`

```lua
-- Keep the screensaver/lock from kicking in while gaming: inhibit idle for
-- any window that goes fullscreen (covers Steam games, emulators, etc. that
-- Omarchy doesn't already special-case).
o.window({ fullscreen = true }, { idle_inhibit = "fullscreen" })
```
which does work when playing skyrim full screen but obviously would cause issues if we left any fullscreen app visible. clanker found the window name and offered this more tailored solution


```bash
# move steam to desktop 2
# launch skyrim
# SUPER+1 to go back to your terminal
# list all client class and title
> hyprctl clients -j | jq -r '.[] | "\(.initialClass) | \(.initialTitle)"'
steam | Steam
steam_app_72850 | Skyrim # <<< use this one
foot | foot
chromium | New Tab - Chromium
org.omarchy.agent | foot
foot | foot
```

```lua
-- Keep the screensaver/lock from kicking in while playing Skyrim.
o.window("steam_app_72850", { idle_inhibit = "always" })
```

this survives game restarts. clanker claims the number is the steam game id and will never change

**Comment by JaviBasulto** [comment]
Still happening on Omarchy 4.0.2 with a different game and input device — adding my case for the record.

**Game:** Uncrashed : FPV Drone Simulator (Steam App ID 1682970)
**Input device:** STMicroelectronics BETAFPV Joystick (USB HID, `/dev/input/js0`, drivers: hid-generic + usbhid)
**Symptom:** Screensaver activates after ~2m30s of gameplay with the joystick, even though the game is running in fullscreen and I'm actively controlling the drone. No keyboard/mouse input during play.

**Key detail:** This did **not** happen on Kubuntu (KDE Plasma) with the same joystick and same game. The screensaver stayed off during gameplay there. The issue appeared after migrating to Omarchy.

**Why I think this matters for the fix:**
The Quickshell IdleMonitor (`respectInhibitors: true`) only defers to explicit XDG/Wayland idle inhibitors sent by the application. Uncrashed/Steam on Wayland apparently doesn't send one (I checked `systemd-inhibit --list` during gameplay — no Steam/Uncrashed inhibitor present). And the BETAFPV joystick only generates ABS/KEY events that Hyprland doesn't treat as "user activity" for idle detection.

So the `idleinhibit fullscreen` windowrule from #1303 might help if the game is truly fullscreen exclusive, but:
1. If the game is borderless/windowed, the rule won't match
2. Even with the rule, if the joystick input doesn't count as activity, the idle timer might still fire if the game doesn't send an inhibitor

**Workaround that works for me:** `omarchy toggle idle stay-awake` before playing. But it's manual per-session.

**Question for the maintainers:** Does the fix in #1303 cover gamepad/joystick-only fullscreen games, or is the `idleinhibit fullscreen` rule only triggered by specific window classes? If it's the latter, would a more general approach (e.g., treating any fullscreen window as idle-inhibited, or counting evdev/joystick events as activity) be worth considering?
