### ISSUE TITLE
macbook 12 2015 keyboard, bluetooth and touchpad do not work

### ISSUE THREAD

**Issue by meceo** [basecamp/omarchy#1768]
### System details

macbook 12 2015, omarchy 3.0.1

### What's wrong?

I tested the macbook compatibility on my old, but fully functional macbook 12 2015. After selecting grub2 installation mode the keyboard stopped working. I was able to successfully install omarchy 3.0 using external keyboard and mouse. Any chance to add the drivers for the model?

**Comment by ryanrhughes** [comment]
Resolved in [v3.0.2](https://github.com/basecamp/omarchy/releases/tag/v3.0.2)

**Comment by meceo** [comment]
I am installing Omarchy 3.0.2 now, but already in installation process the keyboard is not working. Is that expected behavior?

I continue with the installation using external keyboard and see if it's still the case once Omarchy is installed.

**Comment by meceo** [comment]
The OS is installed, I installed all the updates - keyboard and touchpad still don't work. The keyboard works until I select omarchy to start booting, on password screen it does not work.

**Comment by alock** [comment]
I have the same issue with the same hardware.  (MacBook8,1)

When I attempted to update an existing omarchy install to 3.0.2 I noticed that it didn't create the `/etc/mkinitcpio.conf.d/macbook_spi_modules.conf` file.  After running the the script myself I do see the file but the built-in keyboard and trackpad still do not work.

Linking https://github.com/basecamp/omarchy/issues/2099

**Comment by coopenstein** [comment]
Also related to #1954, which has detailed logs and repro steps.
