### ISSUE TITLE
Waybar stacks when waking from sleep

### ISSUE THREAD

**Issue by dhh** [basecamp/omarchy#196]
How high can your waybar go? Apparently quite high!

<img width="3628" height="944" alt="Image" src="https://github.com/user-attachments/assets/a1a016f0-c095-4d60-8793-afd9ba95ed1c" />

**Comment by ryanrhughes** [comment]
This appears to be somewhat linked to an open issue and in this comment https://github.com/Alexays/Waybar/issues/3344#issuecomment-2390661508, specifically some issues with the handler for `SIGUSR2` effectively meaning `pkill -SIGUSR2 waybar` doesn't solve the issue, it causes it. 

This comment has one potential workaround https://github.com/Alexays/Waybar/issues/3344#issuecomment-3048824798. 

Additionally, since we're launching Hyprland with UWSM now, it's also possible we could / should have UWSM manage Waybar as well which may give us a way to eliminate the need to use `SIGUSR2` to terminate it and resolve the issue.

On other dotfile instances, I've seen them use something like this used to restart Waybar to avoid the issue.

```
killall waybar || true
pkill waybar || true
sleep 0.5
waybar
```

**Comment by danfascia** [comment]
For me this happens in the following situations:
- Screen has gone to sleep but PC still on
- Natural time elapsed sleep
- Typically I see 5 x bars as standard after entering wake-up password

Does not happen when:
- I manually invoke suspend (super-esc)

I manually fix it without a reboot with `pkill -SIGUSR2 waybar`

**Comment by abenz1267** [comment]
> This appears to be somewhat linked to an open issue and in this comment [Alexays/Waybar#3344 (comment)](https://github.com/Alexays/Waybar/issues/3344#issuecomment-2390661508), specifically some issues with the handler for `SIGUSR2` effectively meaning `pkill -SIGUSR2 waybar` doesn't solve the issue, it causes it.
> 
> This comment has one potential workaround [Alexays/Waybar#3344 (comment)](https://github.com/Alexays/Waybar/issues/3344#issuecomment-3048824798).
> 
> Additionally, since we're launching Hyprland with UWSM now, it's also possible we could / should have UWSM manage Waybar as well which may give us a way to eliminate the need to use `SIGUSR2` to terminate it and resolve the issue.
> 
> On other dotfile instances, I've seen them use something like this used to restart Waybar to avoid the issue.
> 
> ```
> killall waybar || true
> pkill waybar || true
> sleep 0.5
> waybar
> ```

running with uwsm would be the correct approach. You'd then also use `uuctl` (script in the uwsm repo) to manage the services via dmenu. In my case it looks like this:

<img width="610" height="490" alt="Image" src="https://github.com/user-attachments/assets/9212d536-85b9-4870-8aa3-943ef23c22a6" />

This is an overall much better approach.

**Comment by ryanyogan** [comment]
I was running into this challenge with a frozen machine and many waybars after waking up the system from sleep, I believed it to be related to https://github.com/basecamp/omarchy/issues/26 originally.

Modifying my `hypridle.conf` to the below changes allows my machine to remain stable; however, I need to manually put the machine to sleep in the interim.  This is a band-aid I am using from the mentioned https://github.com/basecamp/omarchy/issues/26 comments.

```bash
general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
   
    # Commenting out dpms 
    # before_sleep_cmd = loginctl lock-session    # lock before suspend.
    # after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 300                      # 5min
    on-timeout = loginctl lock-session # lock screen when timeout has passed
}

listener {
    # Do not dispatch dpms off, essentially, do not sleep for now

    # timeout = 330                                            # 5.5min
    # on-timeout = hyprctl dispatch dpms off                   # screen off when timeout has passed
    # on-resume = hyprctl dispatch dpms on && brightnessctl -r # screen on when activity is detected
}
```

**Comment by dhh** [comment]
If anyone is still seeing this after upgrading to Omarchy 1.5, please let me know in this thread. There was a theory that it was related to USRSIG2, and we've gotten rid of that.

**Comment by martin-ro** [comment]
yeah, unfortunately still happening for me

**Comment by ituri** [comment]
> If anyone is still seeing this after upgrading to Omarchy 1.5, please let me know in this thread. There was a theory that it was related to USRSIG2, and we've gotten rid of that.

That would be me. This issue started appearing after the update to Omarchy 1.5!

**Comment by CyphrRiot** [comment]
new `autostart.conf`

```
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- mako
exec-once = pkill waybar 2>/dev/null || true; sleep 1; uwsm app -- waybar
exec-once = uwsm app -- fcitx5
exec-once = uwsm app -- swaybg -i ~/.config/omarchy/current/background -m fill
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = wl-clip-persist --clipboard regular --all-mime-type-regex '^(?!x-kde-passwordManagerHint).+'
```

**Comment by dhh** [comment]
`exec-once` is only run on startup, so doesn't help to have any pkill waybar stuff in there.

**Comment by dhh** [comment]
I haven't been able to replicate this lately, but for people who are dealing with it, here's a blunt instrument fix:

```
general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
    on_unlock_cmd = pkill waybar && uwsm app -- waybar # FIXME: Temp fix to address stacking waybars
}
```

Replace the general block in `~/.config/hypr/hyprland.conf` with that. It'll restart waybar whenever you unlock, so stacking is cured.

**Comment by dhh** [comment]
This is fixed on dev now using SIGUSR2 instead of a full kill. I just saw it myself.

**Comment by zaneschepke** [comment]
I still see two stacked waybars when waking up from sleep + session unlock. 

Anyone else?

Omarchy 1.7.0

**Comment by martin-ro** [comment]
> I still see two stacked waybars when waking up from sleep + session unlock.
> 
> Anyone else?
> 
> Omarchy 1.7.0

Yep, me. The longer the computer sleeps the more waybars it seems.
