### ISSUE TITLE
Screen is stuttering and background is unusually visible

### ISSUE THREAD

**Issue by oxidebits** [basecamp/omarchy#2340]
### System details

i5 12500H, Intel Xe Graphics,  Omarchy 3.0.2

### What's wrong?

The screen is freezing and pixels blocks are shown and flickering. For the starting few seconds, when recording with obs ,its showing black screen. Later the display is recorded.

https://github.com/user-attachments/assets/28ae819e-6c9c-447f-863b-aad076a5fe78

**Comment by ghost** [comment]
do you have scaling set fractionally?

this is unfortunately a fairly common bug with fractional scaling

**Comment by dhh** [comment]
This has been fixed in hyprutils. Update > Omarchy and the fix will be applied.

**Comment by ryuhzk** [comment]
But we can not update the system cz there have another issue https://github.com/basecamp/omarchy/issues/2307 not fixed yet.  If we updated it then we have to restore the system.

**Comment by mmsbrggr** [comment]
@dhh After some investigation it seems that `hyprutils v0.10` breaks or is incompatible with `hyprpm` (hyprlands plugin manager). Loading a plugin causes Hyprland to crash.

Very unfortunate is that, usually, people have an `exec-once` command to load hyprpm plugins in their Hyprland configuration, causing the `omarchy-seamless.login.service` to fail.

I documented this in my issue: https://github.com/basecamp/omarchy/issues/2307
