### ISSUE TITLE
Screensaver shows error instead of playing animations

### ISSUE THREAD

**Issue by revan1611** [basecamp/omarchy#3561]
### System details

Omarchy 3.2.0

### What's wrong?

Error message:

```
omarchy-cmd-screensaver
usage: tte [-h] [--input-file INPUT_FILE] [--version] [--tab-width (int > 0)] [--xterm-colors] [--no-color] [--existing-color-handling {always,dynamic,ignore}] [--wrap-text] [--frame-rate FRAME_RATE]
           [--canvas-width int >= -1] [--canvas-height int >= -1] [--anchor-canvas {sw,s,se,e,ne,n,nw,w,c}] [--anchor-text {n,ne,e,se,s,sw,w,nw,c}] [--ignore-terminal-dimensions] [--no-eol]
           {beams,binarypath,blackhole,bouncyballs,bubbles,burn,colorshift,crumble,decrypt,errorcorrect,expand,fireworks,highlight,laseretch,matrix,middleout,orbittingvolley,overflow,pour,print,rain,randomsequence,rings,scattered,slice,slide,spotlights,spray,swarm,sweep,synthgrid,unstable,vhstape,waves,wipe} ...
tte: error: argument {beams,binarypath,blackhole,bouncyballs,bubbles,burn,colorshift,crumble,decrypt,errorcorrect,expand,fireworks,highlight,laseretch,matrix,middleout,orbittingvolley,overflow,pour,print,rain,randomsequence,rings,scattered,slice,slide,spotlights,spray,swarm,sweep,synthgrid,unstable,vhstape,waves,wipe}: invalid choice: 'random_effect' (choose from beams, binarypath, blackhole, bouncyballs, bubbles, burn, colorshift, crumble, decrypt, errorcorrect, expand, fireworks, highlight, laseretch, matrix, middleout, orbittingvolley, overflow, pour, print, rain, randomsequence, rings, scattered, slice, slide, spotlights, spray, swarm, sweep, synthgrid, unstable, vhstape, waves, wipe)
ok
```

**Comment by brenoepics** [comment]
I've got the same issue, would you be able to run `tte --version`?

me:
```
~ ❯ tte --version
TerminalTextEffects 0.12.1
```

if you check `tte` releases, [here](https://github.com/ChrisBuilds/terminaltexteffects/releases/tag/release-0.13.0)

`random_effect` was added at 0.13.0 release so I think we are running an old version of tte.

I installed `terminaltexteffects-git` via `yay -S terminaltexteffects-git` so that I could get the latest version from their git and the screensaver is fixed.


I'm not really a Linux user so I may be wrong somewhere here but AUR version seems not up-to-date.


EDIT:
Actually this issue is a duplicate of https://github.com/basecamp/omarchy/issues/3532

**Comment by sltn-s** [comment]
Try run `omarchy-refresh-pacman` and then run `sudo pacman -Syu`.

**Comment by ryanrhughes** [comment]
`omarchy-update` should resolve this as https://github.com/basecamp/omarchy/blob/master/migrations/1763561396.sh has this in it.

**Comment by jfbourdeau** [comment]
Updated, rebooted and still see this.  Didn't have this problem with previous  version ( installaled 1-2 week ago for the 1st time ) the new 3.2 caused this  
<img width="1245" height="940" alt="Image" src="https://github.com/user-attachments/assets/46aacaa1-d947-46c6-9b2e-3db281823a2d" />
samething here
