### ISSUE TITLE
After using emoji picker via Super+Space + ':' the omarchy menu (Super+Alt+Space) and hotkeys overview (Super+K) is rendered in grid mode instead of list

### ISSUE THREAD

**Issue by Matreddit** [basecamp/omarchy#3630]
### System details

Omarchy 3.2.0

### What's wrong?

After updating to Omarchy 3.2.0, I noticed a problem with menu display modes. Normally, the Omarchy menu (Super+Alt+Space) is shown as list. However, if I open the emoji picker (Super+Space, then type ':') and then immediately open either the hotkeys overview (Super+K) or the Omarchy menu, they are displayed in grid mode instead of list mode. This makes them difficult to read.

The issue only appears after using the emoji picker. If I close the emoji picker and open the app menu (Super+Space), they return to list mode.

**Steps to reproduce:**
1. Open the emoji picker with Super+Space, then type ':' to enter emoji selection.
2. Close the emoji picker.
3. Open the Omarchy menu (Super+Alt+Space) or the hotkeys overview (Super+K).

**Expected behavior:**
All menus should return to list mode automatically, so I don’t have to open the app menu to see the Omarchy menu or hotkeys in normal list mode after using the emoji menu.

**Actual behavior:**
Only opening the app menu switches the menus back to list mode; the Omarchy menu and hotkeys remain in grid mode otherwise.

<img width="828" height="752" alt="Image" src="https://github.com/user-attachments/assets/636f37b2-38b8-4f75-a031-6b89e044a110" />

<img width="425" height="309" alt="Image" src="https://github.com/user-attachments/assets/3a036cd5-350c-47b9-92f3-c9ea37e6f970" />

**Comment by dhh** [comment]
I've replicated this. This looks like a bug, @abenz1267. That it's remembering this grid setup for later invocations.

**Comment by abenz1267** [comment]
fixed

**Comment by yaroslavrick** [comment]
Still reproducible on Omarchy 3.2.1 (but I do not think that it is a problem)
