### ISSUE TITLE
Hyprland config errors after Omarchy update (invalid options and window rules)

### ISSUE THREAD

**Issue by numanzahid** [basecamp/omarchy#4023]
### System details

Omarchy 3.2.3, Latitude 7390 2-in-1

### What's wrong?

After Omarchy update, Hyprland continuously displays config errors on screen.

Errors shown:
misc:new_window_takes_over_fullscreen does not exist
invalid field type: suppressevent
invalid field class/nofocus: missing a value

The errors seem to be coming from config files:
~/.local/share/omarchy/default/hypr/looknfeel.conf
~/.local/share/omarchy/default/hypr/windows.conf

Environment:
Linux omarchy 6.18.2-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 18 Dec 2025 18:00:18 +0000 x86_64 GNU/Linux
Hyperland: 0.53.0-2

<img width="1897" height="242" alt="Image" src="https://github.com/user-attachments/assets/aa5346ba-39fa-4de8-9636-b40739522f02" />

Hoping to find help soon, the errors are very annoying. :)

**Comment by goinggentle** [comment]
Seeing exact same issue just now after using manual Omarchy install script on fresh Arch install

**Comment by ghrubi** [comment]
Hyprland just released a new version with new windows rules syntax among other things. 

Windowrule syntax has been completely overhauled. Please check the wiki: https://wiki.hypr.land/Configuring/Window-Rules/

Also, 
misc:new_window_takes_over_fs replaces misc:new_window_takes_over_fullscreen and master:inherit_fullscreen

https://github.com/hyprwm/Hyprland/releases/tag/v0.53.0

**Comment by LunarLollipop** [comment]
Fix: https://github.com/basecamp/omarchy/pull/4025

**Comment by numanzahid** [comment]
@LunarLollipop 

there are more errors, most likely after the hyperland update.

`
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/1password.conf at line 1: invalid field noscreenshare: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/1password.conf at line 2: invalid field class:^(1[p|P]assword)$: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/bitwarden.conf at line 1: invalid field noscreenshare: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/bitwarden.conf at line 2: invalid field class:^(Bitwarden)$: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/browser.conf at line 10: invalid field tag:firefox-based
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/browser.conf at line 10: invalid field tag:firefox-based-browser: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/browser.conf at line 13: invalid field initialTitle:((?i)(?:[a-z0-9-]+\.)*youtube\.com_/|app\.zoom\.us_/wc/home): missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/browser.conf at line 2: invalid field class:((google-)?[cC]hrom(e|ium)|[bB]rave-browser|[mM]icrosoft-edge|Vivaldi-stable|helium): missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/browser.conf at line 3: invalid field class:([fF]irefox|zen|librewolf): missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/browser.conf at line 6: invalid field tile: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/browser.conf at line 9: invalid field tag:chromium-based-browser: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps.conf at line 2: Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/1password.conf at line 1: invalid field noscreenshare: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps.conf at line 3: Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/1password.conf at line 1: invalid field noscreenshare: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps.conf at line 4: Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/1password.conf at line 1: invalid field noscreenshare: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps.conf at line 5: Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/1password.conf at line 1: invalid field noscreenshare: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps.conf at line 6: Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/1password.conf at line 1: invalid field noscreenshare: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps.conf at line 7: Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/1password.conf at line 1: invalid field noscreenshare: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps.conf at line 8: Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/1password.conf at line 1: invalid field noscreenshare: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps.conf at line 9: Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/1password.conf at line 1: invalid field noscreenshare: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/hyprshot.conf at line 2: invalid field noanim: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 12: invalid field stayfocused: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 13: invalid field noborder: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 16: invalid field class:^(jetbrains-.*): missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 19: invalid field noinitialfocus: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 22: invalid field nofollowmouse: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 2: invalid field class:^(jetbrains-.*)$: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 3: invalid field center: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 4: invalid field nofocus: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 5: invalid field noborder: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 8: invalid field class:^(jetbrains-.*): missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/jetbrains.conf at line 9: invalid field center: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/localsend.conf at line 2: invalid field float: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/localsend.conf at line 3: invalid field center: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/pip.conf at line 2: invalid field title:(Picture.?in.?[Pp]icture): missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/pip.conf at line 3: invalid field float: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/pip.conf at line 4: invalid field pin: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/pip.conf at line 5: invalid field tag:pip: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/pip.conf at line 6: invalid field keepaspectratio: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/pip.conf at line 7: invalid field noborder: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/pip.conf at line 8: invalid field tag:pip: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/pip.conf at line 9: invalid field tag:pip: missing a value
Config error in file /home/numan/.local/share/omarchy/default/hypr/apps/qemu.conf at line 1: invalid field class:qemu: missing a value
`

**Comment by LunarLollipop** [comment]
@numanzahid yep those are the exact errors this PR fixes! all the old syntax like `noscreenshare`, `class:`, `noborder`, `float` etc changed in hyprland 0.53

**Comment by LunarLollipop** [comment]
> Hyprland just released a new version with new windows rules syntax among other things.
> 
> Windowrule syntax has been completely overhauled. Please check the wiki: https://wiki.hypr.land/Configuring/Window-Rules/
> 
> Also, misc:new_window_takes_over_fs replaces misc:new_window_takes_over_fullscreen and master:inherit_fullscreen
> 
> https://github.com/hyprwm/Hyprland/releases/tag/v0.53.0

new_window_takes_over_fs -> on_focus_under_fullscreen

https://github.com/hyprwm/Hyprland/discussions/12749

**Comment by numanzahid** [comment]
@LunarLollipop Thank for the update.
I switch /omarchy branch from master to your pr. and all errors are gone. screensaver is also loading in fullscreen. looks like all the problems are solved. only errors were about input from the /hypr/input.conf file. 

Commented out these two line, and those errors are gone as well. 
windowrule = scrolltouchpad 1.5, class:(Alacritty|kitty)
windowrule = scrolltouchpad 0.2, class:com.mitchellh.ghostty

**Comment by amir-autom8labs** [comment]
When can we expect this PR to be merged ? Should we wait for it or look for manual fix ? is there some known workaround ?

**Comment by thaian1892001** [comment]
I'm on CatchyOS with HyDE installed and get the exact same issue

**Comment by michael-maheriniaina** [comment]
You can fix the error manually by following the changes on latest wiki https://wiki.hypr.land/Configuring/Window-Rules/

**Comment by mmlo** [comment]
> Fix: [#4025](https://github.com/basecamp/omarchy/pull/4025)

Thanks @LunarLollipop

**Comment by Riddlerrr** [comment]
If you want to wait an official Omarchy fix you can switch to Stable channel and downgrade the installed packages to the stable versions as a workaround:

1. Omarchy menu -> Update -> Clannel -> Stable
2. run `sudo pacman -Syuu` to downgrade packages. `uu` allow pacman to downgrade.
3. Restart the Omarchy

**Comment by goinggentle** [comment]
> If you want to wait an official Omarchy fix you can switch to Stable channel and downgrade the installed packages to the stable versions as a workaround:

Is Omarchy not using the stable channel by default? I used the manual installation script last night and it installed Hyperland: 0.53 with all the config errors.

**Comment by Riddlerrr** [comment]
> Is Omarchy not using the stable channel by default?

I'm not sure, I was on Edge channel but I switched to it manually.

**Comment by goinggentle** [comment]
Sorry am new here, but it looks like since https://github.com/basecamp/omarchy/releases/tag/v3.2.0, the stable mirror should be the default.

It seems like new installations are not pulling from the stable channel, which is an issue that should also be fixed.

**Comment by eososlinux** [comment]
> If you want to wait an official Omarchy fix you can switch to Stable channel and downgrade the installed packages to the stable versions as a workaround:
> 
> 1. Omarchy menu -> Update -> Clannel -> Stable
> 2. run `sudo pacman -Syuu` to downgrade packages. `uu` allow pacman to downgrade.
> 3. Restart the Omarchy

Este metodo no va servir.

1-instalar downgrade
yay -S downgrade

2- sudo downgrade hyprland
seleccionar la version hyprland-0.52.2-3-x86_64 se abre fzf

3-agregar hyprland al archivo pacman.conf
warning: downgrading package hyprland (0.53.0-2 => 0.52.2-3)
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version  New Version  Net Change

hyprland     0.53.0-2     0.52.2-3       2.23 MiB

Total Installed Size:  61.81 MiB
Net Upgrade Size:       2.23 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring  
(1/1) checking package integrity 
(1/1) loading package files 
(1/1) checking for file conflicts 
(1/1) checking available disk space 
:: Running pre-transaction hooks...
(1/1) Wait for limine-snapper-sync to finish...
:: Processing package changes...
(1/1) downgrading hyprland  
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
add hyprland to IgnorePkg? [y/N] y

Cuando este disponible la actualizacion de los archivos de punto primero debes quitar hyprland del archivo pacman.conf, despues actualizar los paquetes y archivos de punto.

**Comment by dhh** [comment]
This isn't an issue on stable because stable doesn't have 0.53. Good reminder to be on that, so that issues on edge can be sorted by folks willing and eager to dive into that.

**Comment by maxguzenski** [comment]
I think that when an Omarchy installation is on the edge channel, it should also go into the dev branch, or into some other branch specifically made to receive these fixes.

**Comment by Britnell** [comment]
+1 ....

**Comment by Shaeldor** [comment]
i also stumbled upon this code converter that fixed a similiar issue:
https://itsohen.github.io/hyprrulefix/
It automatically fixed my .conf file

**Comment by marcantonio** [comment]
I think there's something else going on here as well. I've installed Omarchy from a fresh Arch install twice over the last 2 days via `curl -fsSL https://omarchy.org/install | bash` and both times 0.53 was installed. On the last one I confirmed I was on stable before rebooting with:

```
$ grep Server /etc/pacman.conf
Server = https://pkgs.omarchy.org/stable/$arch
$ cd ~/.local/share/omarchy; git branch
* master
$ pacman -Q hyprland
hyprland 0.53.0-2
```

I think that means I'm on stable? Regardless, I just downgraded with `sudo pacman -U https://archive.archlinux.org/packages/h/hyprland/hyprland-0.52.2-3-x86_64.pkg.tar.zst`.

**Comment by dhh** [comment]
This must be a bug where we end up setting the pkgs repository too late when doing a manual install. I'll investigate this. Thanks! On the ISO, the correct package repository is set early, and the default packages are thus only the certified ones.

**Comment by Smittttttt** [comment]
until an official fix comes from omarchy we can just hide the errors aswell.
`debug {
    suppress_errors = true
}`
put this in hyprland config

**Comment by nakajimayoshi** [comment]
Did any of the maintainers of omarchy not catch these hyprland configuration errors before releasing a distro update? Was there a plan to release a new config supporting the updated syntax?

**Comment by dhh** [comment]
The dev branch is compatible with 0.53. The stable version of Omarchy's mirrors have not upgraded to 0.53. You should run on the stable channel to avoid any incompatibilities.

There's a new release coming very shortly, though.

**Comment by bessonette** [comment]
I had the issue as well. I've been on the Stable channel, but I did install manually.

**Comment by dhh** [comment]
Unfortunately the manual installs have not been setting the mirror to stable. Run omarchy-refresh-pacman to do that. This is fixed in Omarchy 3.3.

**Comment by phenomen** [comment]
After the update to 3.3.0 my whole UI is completely borked and I barely changed any configs (just disabled window transparency and blur in `looknfeel.conf`).

- no top bar 
- tons of errors in many configs that I never touched, including default themes
- windows have no background
- automated rule converter does not fix issues

Is there a way to reset/restore ALL configs to default?

**Comment by dhh** [comment]
Yes, you can run `omarchy-reinstall-configs`. What version were you upgrading from?

**Comment by bscott** [comment]
I'm now getting this same error after updating to Omarchy 3.3.0, issue #4134 

I'll try omarchy-reinstall-configs, but error is still there. Uprading from 3.2.3 --> 3.3.0. 

Update: reran `omarchy-update` and it resolved.

**Comment by dhh** [comment]
The original issue has been fixed with the 3.3.0 release. All Omarchy system files are now compatible with Hyprland 0.53. If you have user configs that need to change, see the link in the release notes for help 👌

**Comment by fury-of-de-night** [comment]
i updated and got thru with most of the errors going away but just a few remained i got that fixed 
the no screenshare in hypr congif
/home/{name}/.config/omarchy/current/theme/hyprland.conf
was this and was giving errors
line 48 and 49
48  windowrule = noscreenshare, class:proton-authenticator
49  windowrule = noscreenshare, title:Proton Authenticator

this fixed it
windowrule = no_screen_share on, match:class proton-authenticator
windowrule = no_screen_share on, match:title "Proton Authenticator"

**Comment by Swader** [comment]
I ran omarchy-reinstall-configs but now after a reboot the error is still there and my shortcut for opening the terminal is no longer working for me to run omarchy-update through.

<img width="4032" height="3024" alt="Image" src="https://github.com/user-attachments/assets/fd98abd9-5faa-438d-a7e9-b49b38f992c2" />

Anything I can do to bypass this problem?

Limine snapshots don't help. In fact, they are also broken because the config is kept across snapshots, meaning the config reset I did borked my terminal access across all the snapshots too.

I got into TTY with CTRL ALT F2. Found omarchy-update and omarchy-reinstall in .local.

When I run omarchy-update, I get omarchy-update-confirm command not found.
When I run omarchy-reinstall, I get omarchy-reinstall-git command not found.

Once I exported path `export PATH="$HOME/.local/share/omarchy/bin:$PATH"` I managed to run it, but got

```
cat /version: No such file or directory

Something went wrong during the update!
```

Running reinstall after the export cloned into omarchy-new, but then stopped the process at:

```
mv: missing destination file operand after .../share/omarchy-old
```

I tried to re-clone from github.com/basecamp/omarchy.git, switching to master branch, and re-running those 2 commands but I get the same output.

**Comment by dhh** [comment]
Looks like you don't have omarchy in path, which would be due to uwsm not starting. I haven't seen that one before. How old was the install before you upgraded? Check if `~/.config/uwsm/env` exists. Did you mess with the uwsm or sddm setup?

**Comment by numanzahid** [comment]
Did you try config reset? 
Omarchy menu > setup > config > defaults

> I ran omarchy-reinstall-configs but now after a reboot the error is still there and my shortcut for opening the terminal is no longer working for me to run omarchy-update through.
> 
> <img width="4032" height="3024" alt="Image" src="https://github.com/user-attachments/assets/fd98abd9-5faa-438d-a7e9-b49b38f992c2" />
> 
> Anything I can do to bypass this problem?
> 
> Limine snapshots don't help. In fact, they are also broken because the config is kept across snapshots, meaning the config reset I did borked my terminal access across all the snapshots too.
> 
> I got into TTY with CTRL ALT F2. Found omarchy-update and omarchy-reinstall in .local.
> 
> When I run omarchy-update, I get omarchy-update-confirm command not found.
> When I run omarchy-reinstall, I get omarchy-reinstall-git command not found.
> 
> Once I exported path `export PATH="$HOME/.local/share/omarchy/bin:$PATH"` I managed to run it, but got
> 
> ```
> cat /version: No such file or directory
> 
> Something went wrong during the update!
> ```
> 
> Running reinstall after the export cloned into omarchy-new, but then stopped the process at:
> 
> ```
> mv: missing destination file operand after .../share/omarchy-old
> ```
> 
> I tried to re-clone from github.com/basecamp/omarchy.git, switching to master branch, and re-running those 2 commands but I get the same output.

**Comment by Swader** [comment]
> How old was the install before you upgraded? Check if ~/.config/uwsm/env exists. Did you mess with the uwsm or sddm setup?

I installed in October last year. I never fiddled with uwsm or sddm. I basically set it up, made sure it works, installed some custom official theme to make it pretty, and left it like this for 3 months.
I already formatted to reinstall everything, I didn't do any work on this machine yet so no harm done, seemed faster.

@numanzahid 
> Did you try config reset?
> Omarchy menu > setup > config > defaults

There was no menu. The UI completely failed on all levels so I couldn't use any function of Omarchy UI at all.
